# harness.io/skip-file-for-deploy
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-job
spec:
  template:
    spec:
      containers:
      - name: pi
        image: python:3.6.12-alpine
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
