apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  annotations:
{{ .Values.cm.annotations | toYaml | indent 4}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: {{.Values.name}}
